<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Audit Log · District 23 FYS</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=Material+Symbols+Outlined" rel="stylesheet"><script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="min-h-screen bg-[#f9f9ff] font-[Inter] text-[#111c2d] antialiased">
@include('admin.partials.header')
<aside class="fixed bottom-0 left-0 top-16 hidden w-64 bg-[#f0f3ff] py-6 lg:flex lg:flex-col"><div class="px-6 pb-4 text-[11px] font-bold uppercase tracking-wider text-[#44474c]">Navigation</div><nav class="flex flex-col gap-1 px-2"><a href="{{ route('admin.dashboard') }}" class="flex items-center gap-2 rounded px-4 py-2.5 text-sm text-[#44474c] transition hover:bg-[#dee8ff]"><span class="material-symbols-outlined text-xl">dashboard</span>Dashboard</a><a href="{{ route('admin.voter-management') }}" class="flex items-center gap-2 rounded px-4 py-2.5 text-sm text-[#44474c] transition hover:bg-[#dee8ff]"><span class="material-symbols-outlined text-xl">badge</span>Voter Management</a><a href="{{ route('admin.position-management') }}" class="flex items-center gap-2 rounded px-4 py-2.5 text-sm text-[#44474c] transition hover:bg-[#dee8ff]"><span class="material-symbols-outlined text-xl">work</span>Position Management</a><a href="{{ route('admin.results-document-preview') }}" class="flex items-center gap-2 rounded px-4 py-2.5 text-sm text-[#44474c] transition hover:bg-[#dee8ff]"><span class="material-symbols-outlined text-xl">description</span>Results &amp; Document Preview</a><a aria-current="page" href="{{ route('admin.audit-log') }}" class="flex items-center gap-2 rounded border-l-4 border-[#ffdf98] bg-[#dee8ff] px-4 py-2.5 pl-5 text-sm font-bold text-[#115cb9]"><span class="material-symbols-outlined text-xl">history_edu</span>Audit Log</a></nav></aside>
<main class="min-h-screen px-4 pb-10 pt-24 sm:px-6 lg:ml-64"><div class="mx-auto max-w-6xl"><section class="rounded-xl bg-white p-6 shadow-sm"><p class="text-[11px] font-bold uppercase tracking-wider text-[#115cb9]">Stored election records</p><h1 class="mt-2 text-3xl font-bold">AUDIT LOG</h1><p class="mt-2 text-sm text-[#44474c]">Archived ballot-position results saved before an election reset.</p></section><section class="mt-6 rounded-xl bg-white p-6 shadow-sm"><div class="mt-4 space-y-3">@forelse ($auditLogs as $auditLog)<a href="{{ route('admin.audit-log.show', $auditLog) }}" class="flex items-center justify-between gap-4 rounded-lg border border-slate-200 p-4 transition hover:border-[#115cb9] hover:bg-[#f0f3ff]"><div><p class="font-bold">{{ $auditLog->title }}</p><p class="mt-1 text-sm text-[#44474c]">{{ $auditLog->action }} · {{ $auditLog->created_at->timezone('Asia/Manila')->format('M d, Y h:i A') }}</p></div><span class="shrink-0 rounded bg-[#115cb9] px-4 py-2 text-sm font-bold text-white">VIEW ALL RESET DATA</span></a>@empty<p class="rounded-lg bg-[#f0f3ff] p-4 text-sm text-[#44474c]">No stored election results yet. Reset an election to create an archive.</p>@endforelse</div></section></div></main>
<script src="{{ asset('js/admin-navigation-cleanup.js') }}?v={{ filemtime(public_path('js/admin-navigation-cleanup.js')) }}"></script>
</body></html>
