<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Stored Results · District 23 FYS</title><link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet"><script src="https://cdn.tailwindcss.com"></script></head>
<body class="min-h-screen bg-[#f9f9ff] font-sans text-[#111c2d] antialiased">
@include('admin.partials.header')
<aside class="fixed bottom-0 left-0 top-16 hidden w-64 bg-[#f0f3ff] py-6 lg:flex lg:flex-col"><div class="px-6 pb-4 text-[11px] font-bold uppercase tracking-wider text-[#44474c]">Navigation</div><nav class="flex flex-col gap-1 px-2"><a href="{{ route('admin.dashboard') }}" class="nav"><span class="material-symbols-outlined">dashboard</span><span>Dashboard</span></a><a href="{{ route('admin.voter-management') }}" class="nav"><span class="material-symbols-outlined">badge</span><span>Voter Management</span></a><a href="{{ route('admin.position-management') }}" class="nav"><span class="material-symbols-outlined">work</span><span>Position Management</span></a><a href="{{ route('admin.results-document-preview') }}" class="nav"><span class="material-symbols-outlined">description</span><span>Results &amp; Document Preview</span></a><a aria-current="page" href="{{ route('admin.audit-log') }}" class="nav active"><span class="material-symbols-outlined">history_edu</span><span>Audit Log</span></a></nav></aside>
<main class="min-h-screen px-4 pb-10 pt-24 sm:px-6 lg:ml-64"><div class="mx-auto max-w-6xl"><a href="{{ route('admin.audit-log') }}" class="font-bold text-[#115cb9]">← Back to Audit Log</a><section class="mt-5 rounded-xl bg-white p-6 shadow-sm"><p class="text-[11px] font-bold uppercase tracking-wider text-[#115cb9]">Stored results</p><h1 class="mt-2 text-3xl font-bold">{{ $auditLog->title }}</h1><p class="mt-2 text-sm text-[#44474c]">{{ $auditLog->action }} · {{ $auditLog->created_at->timezone('Asia/Manila')->format('M d, Y h:i A') }}</p><form class="mt-5" method="POST" action="{{ route('admin.audit-log.restore', $auditLog) }}" onsubmit="return confirm('Restore this archived election and replace the current election data?');">@csrf<button class="rounded bg-[#ba1a1a] px-5 py-3 text-sm font-bold text-white hover:bg-[#93000a]" type="submit">RESTORE THIS ELECTION</button></form></section><section class="mt-6 rounded-xl bg-white p-6 shadow-sm"><h2 class="text-2xl font-bold">Results by ballot position</h2><div class="mt-5 space-y-4">@forelse (($auditLog->results['positions'] ?? $auditLog->results ?? []) as $result)<article class="rounded-xl bg-[#f0f3ff] p-5"><div class="flex items-center justify-between gap-4"><div><h3 class="text-2xl font-bold">{{ strtoupper($result['position']) }}</h3><p class="text-sm text-[#44474c]">{{ $result['seats'] }} seat{{ $result['seats'] === 1 ? '' : 's' }} · {{ $result['ballots_cast'] }} ballots cast</p></div><span class="rounded-full bg-emerald-100 px-3 py-2 text-xs font-bold text-emerald-700">STORED</span></div><div class="mt-4 space-y-2">@forelse ($result['winners'] as $winner)<div class="flex items-center justify-between border-b border-white py-2"><span>{{ $loop->iteration }}. {{ $winner['name'] }}</span><strong class="text-[#115cb9]">{{ $winner['votes'] }}</strong></div>@empty<p class="text-sm text-[#44474c]">No winner recorded.</p>@endforelse<div class="flex items-center justify-between border-t border-white pt-2 font-semibold"><span>ABSTAIN</span><strong class="text-[#115cb9]">{{ $result['abstentions'] }}</strong></div></div></article>@empty<p class="rounded-lg bg-[#f0f3ff] p-4 text-sm text-[#44474c]">No stored positions in this archive.</p>@endforelse</div></section></div></main>
<style>.nav{display:flex;align-items:center;gap:.75rem;border-radius:.25rem;padding:.75rem 1rem;font-size:.875rem;color:#44474c}.nav:hover,.nav.active{background:#dee8ff;color:#115cb9}.nav.active{border-left:4px solid #ffdf98;padding-left:.75rem;font-weight:700}.material-symbols-outlined{font-size:22px;line-height:1}</style>
<script src="{{ asset('js/admin-navigation-cleanup.js') }}?v={{ filemtime(public_path('js/admin-navigation-cleanup.js')) }}"></script>
</body></html>
