<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Candidates &amp; Nominations | District 23 FYS</title>
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=Outfit:wght@600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined&display=swap" rel="stylesheet">
</head>
<body class="min-h-screen bg-[#f9f9ff] font-[Inter] text-[#111c2d] antialiased">
    @include('admin.partials.header')
    <aside class="fixed bottom-0 left-0 top-16 z-40 hidden w-64 bg-[#f0f3ff] py-6 lg:flex lg:flex-col"><div class="px-6 pb-4 text-[11px] font-bold uppercase tracking-wider text-[#44474c]">Navigation</div><nav class="flex flex-col gap-1 px-2"><a href="{{ route('admin.dashboard') }}" class="rounded px-4 py-2.5 text-sm text-[#44474c]">Dashboard</a><a href="{{ route('admin.voter-management') }}" class="rounded px-4 py-2.5 text-sm text-[#44474c]">Voter Management</a><a href="{{ route('admin.position-management') }}" class="rounded px-4 py-2.5 text-sm text-[#44474c]">Position Management</a><a href="{{ route('admin.candidates-nominations') }}" class="rounded border-l-4 border-[#ffdf98] bg-[#dee8ff] px-4 py-2.5 text-sm font-bold text-[#115cb9]">Candidates &amp; Nominations</a><a href="{{ route('admin.results-document-preview') }}" class="rounded px-4 py-2.5 text-sm text-[#44474c]">Results &amp; Document Preview</a><a href="{{ route('admin.audit-log') }}" class="rounded px-4 py-2.5 text-sm text-[#44474c]">Audit Log</a></nav></aside>
    <main class="min-h-screen bg-[#f9f9ff] px-4 pb-10 pt-24 sm:px-6 lg:ml-64"><div class="mx-auto flex w-full max-w-6xl flex-col gap-6">
        <section class="rounded-xl bg-white p-5 shadow-sm sm:p-6"><p class="text-[11px] font-bold uppercase tracking-widest text-[#115cb9]">Official Executive Session</p><h1 class="mt-2 font-[Outfit] text-3xl font-bold sm:text-4xl">CANDIDATES &amp; NOMINATIONS</h1><p class="mt-2 text-sm text-[#44474c]">Review, approve, reject, and finalize real candidate submissions.</p></section>
        @if (session('candidate_success'))<div class="rounded-lg bg-emerald-100 p-4 text-sm font-semibold text-emerald-800">{{ session('candidate_success') }}</div>@endif
        @if (!$position)<section class="rounded-xl bg-white p-6 shadow-sm"><p class="text-sm text-[#44474c]">No active election position is available.</p></section>
        @else
            <section class="rounded-xl bg-white p-5 shadow-sm sm:p-6"><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="text-[11px] font-bold uppercase tracking-widest text-[#115cb9]">Current position</p><h2 class="mt-1 font-[Outfit] text-2xl font-bold">{{ strtoupper($position->name) }}</h2><p class="mt-1 text-sm text-[#44474c]">{{ $position->seats }} seat{{ $position->seats === 1 ? '' : 's' }} · {{ $submissions->count() }} submission{{ $submissions->count() === 1 ? '' : 's' }}</p></div><span class="rounded-full bg-[#e7eeff] px-3 py-2 text-xs font-bold text-[#115cb9]">{{ $position->is_unlocked ? 'BALLOT OPEN' : 'BALLOT LOCKED' }}</span></div></section>
            <section class="overflow-hidden rounded-xl bg-white shadow-sm"><div class="overflow-x-auto"><table class="w-full min-w-[700px] text-left text-sm"><thead class="bg-[#f0f3ff] text-xs uppercase tracking-wide text-[#44474c]"><tr><th class="px-5 py-3">Candidate</th><th class="px-5 py-3">Submission type</th><th class="px-5 py-3">Status</th><th class="px-5 py-3 text-right">Actions</th></tr></thead><tbody>@forelse ($submissions as $submission)<tr class="border-t border-[#eef1fa]"><td class="px-5 py-4"><div class="font-semibold">{{ $submission->candidate_name }}</div><div class="text-xs text-[#75777d]">{{ $submission->submitted_by_email }}</div></td><td class="px-5 py-4">{{ $submission->submission_type }}</td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $submission->status === 'Approved' ? 'bg-emerald-100 text-emerald-800' : 'bg-[#ffdf98] text-[#5a4300]' }}">{{ $submission->status }}</span></td><td class="px-5 py-4 text-right"><div class="flex justify-end gap-2">@if ($submission->status === 'Pending')<form method="POST" action="{{ route('admin.candidates-nominations.status', $submission) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="Approved"><button class="rounded bg-[#115cb9] px-3 py-2 text-xs font-bold text-white" type="submit">Approve</button></form><form method="POST" action="{{ route('admin.candidates-nominations.status', $submission) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="Rejected"><button class="rounded bg-[#ffdad6] px-3 py-2 text-xs font-bold text-[#93000a]" type="submit">Reject</button></form>@else<span class="text-xs text-[#75777d]">No action needed</span>@endif</div></td></tr>@empty<tr><td class="px-5 py-10 text-center text-sm text-[#44474c]" colspan="4">No candidacy or nomination submissions yet.</td></tr>@endforelse</tbody></table></div></section>
            <section class="rounded-xl bg-white p-5 shadow-sm sm:p-6"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="font-[Outfit] text-2xl font-bold">FINALIZE CANDIDATES</h2><p class="mt-1 text-sm text-[#44474c]">Finalization approves pending submissions and closes candidacy changes for this position.</p></div><form method="POST" action="{{ route('admin.candidates-nominations.finalize', $position) }}" onsubmit="return confirm('Finalize the candidate list for this position?')">@csrf @method('PATCH')<button class="rounded bg-[#0e1c2f] px-4 py-3 text-xs font-bold text-white" type="submit">FINALIZE CANDIDATES</button></form></div></section>
        @endif
    </div></main>
<script src="{{ asset('js/admin-navigation-cleanup.js') }}?v={{ filemtime(public_path('js/admin-navigation-cleanup.js')) }}"></script>
</body>
</html>
