<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Audit Log · District 23 FYS</title>
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet"><script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="min-h-screen bg-[#f9f9ff] font-sans text-[#111c2d] antialiased">
@include('admin.partials.header')
<aside class="fixed bottom-0 left-0 top-16 hidden w-64 bg-[#f0f3ff] py-6 lg:flex lg:flex-col"><div class="px-6 pb-4 text-[11px] font-bold uppercase tracking-wider text-[#44474c]">Navigation</div><nav class="flex flex-col gap-1 px-2"><a href="{{ route('admin.dashboard') }}" class="nav"><span class="material-symbols-outlined">dashboard</span><span>Dashboard</span></a><a href="{{ route('admin.voter-management') }}" class="nav"><span class="material-symbols-outlined">badge</span><span>Voter Management</span></a><a href="{{ route('admin.position-management') }}" class="nav"><span class="material-symbols-outlined">work</span><span>Position Management</span></a><a href="{{ route('admin.results-document-preview') }}" class="nav"><span class="material-symbols-outlined">description</span><span>Results &amp; Document Preview</span></a><a aria-current="page" href="{{ route('admin.audit-log') }}" class="nav active"><span class="material-symbols-outlined">history_edu</span><span>Audit Log</span></a></nav></aside>
<main class="min-h-screen px-4 pb-10 pt-24 sm:px-6 lg:ml-64"><div class="mx-auto max-w-6xl"><section class="rounded-xl bg-white p-6 shadow-sm"><p class="text-[11px] font-bold uppercase tracking-wider text-[#115cb9]">Stored election records</p><h1 class="mt-2 text-3xl font-bold">AUDIT LOG</h1><p class="mt-2 text-sm text-[#44474c]">Archived ballot-position results saved before an election reset.</p></section><section class="mt-6 rounded-xl bg-white p-6 shadow-sm"><div class="mt-4 space-y-3">@forelse ($auditLogs as $auditLog)<a href="{{ route('admin.audit-log.show', $auditLog) }}" class="flex items-center justify-between gap-4 rounded-lg border border-slate-200 p-4 transition hover:border-[#115cb9] hover:bg-[#f0f3ff]"><div><p class="font-bold">{{ $auditLog->title }}</p><p class="mt-1 text-sm text-[#44474c]">{{ $auditLog->action }} · {{ $auditLog->created_at->timezone('Asia/Manila')->format('M d, Y h:i A') }}</p></div><span class="shrink-0 rounded bg-[#115cb9] px-4 py-2 text-sm font-bold text-white">VIEW ALL RESET DATA</span></a>@empty<p class="rounded-lg bg-[#f0f3ff] p-4 text-sm text-[#44474c]">No stored election results yet. Reset an election to create an archive.</p>@endforelse</div></section></div></main>
<style>.nav{display:flex;align-items:center;gap:.75rem;border-radius:.25rem;padding:.75rem 1rem;font-size:1rem;line-height:1.25;color:#263143;text-decoration:none;transition:background-color .15s ease,color .15s ease}.nav:hover{background:#dee8ff;color:#111c2d}.nav.active{border-left:4px solid #ffdf98;background:#dee8ff;color:#115cb9;padding-left:.75rem;font-weight:700}.material-symbols-outlined{font-size:22px;line-height:1}</style>
<script src="{{ asset('js/admin-navigation-cleanup.js') }}?v={{ filemtime(public_path('js/admin-navigation-cleanup.js')) }}"></script>
</body></html>
